services:
# ================================================
# Database services
# ================================================
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d myapp"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default_network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - default_network

# ================================================
# Miscellaneous services
# ================================================
  scraping_service:
    extends:
      file: ./scraping-service/compose.yml
      service: scraping_service
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/health || exit 1"]
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - default_network

# ================================================
# Jobs
# ================================================
  html_scraper:
    build:
      context: ./html-retrieval-job
    depends_on:
      db:
        condition: service_healthy
      scraping_service:
        condition: service_healthy
    environment:
      - SCRAPING_SERVICE_URL=http://scraping_service:8000/scrape
      - DATABASE_URI=postgresql://myuser:mypassword@db:5432/myapp
      - PAGE_LIMIT=10
      - LISTINGS_FROM=2022-01-01
    networks:
      - default_network

volumes:
  postgres_data:
  pgadmin_data:
  airflow-postgres-db-volume:
    name: airflow-postgres-db-volume

networks:
  default_network:
    driver: bridge