TRANSLATED_FEATURE_MAPPINGS = {
    "features": {
        "separate_entrance": "Atskiras įėjimas",
        "high_ceilings": "Aukštos lubos",
        "attic_apartment": "Butas palėpėje",
        "multi_floor_apartment": "Butas per kelis aukštus",
        "address_registration": "Galima deklaruoti gyvenamąją vietą",
        "pet_friendly": "Galima su gyvūnais",
        "internet": "Internetas",
        "cable_tv": "Kabelinė televizija",
        "flexible_rent_for_ukrainians": "Lankstesnės nuomos sąlygos ukrainiečiams (dėl nuomos laikotarpio, kainos ar kt.). Daugiau informacijos – skelbime nurodytais kontaktais. / Більш гнучкі умови оренди для українців (за рахунок терміну оренди, цін тощо). Більше інформації за контактами, вказаними в оголошенні.",
        "new_electrical_wiring": "Nauja elektros instaliacija",
        "new_sewage_system": "Nauja kanalizacija",
        "separate_wc_and_bathroom": "Tualetas ir vonia atskirai",
        "gated_yard": "Uždaras kiemas",
        "kitchen_living_room": "Virtuvė sujungta su kambariu",
        "elevator": "Yra liftas",
        "help_for_ukrainians": "Допомога українцям",
    },
    "additional_rooms": {
        "balcony": "Balkonas",
        "walk_in_closet": "Drabužinė",
        "sauna": "Pirtis",
        "basement": "Rūsys",
        "storage_room": "Sandėliukas",
        "terrace": "Terasa",
        "parking_space": "Vieta automobiliui",
        "attic": "Yra palėpė",
    },
    "additional_equipment": {
        "shower_cabin": "Dušo kabina",
        "dishwasher": "Indaplovė",
        "air_conditioner": "Kondicionierius",
        "plastic_pipes": "Plastikiniai vamzdžiai",
        "ventilation_system": "Rekuperacinė sistema",
        "washing_machine": "Skalbimo mašina",
        "furnished": "Su baldais",
        "kitchen_set": "Virtuvės komplektas",
        "stove": "Viryklė",
        "bathtub": "Vonia",
        "refrigerator": "Šaldytuvas",
        "heated_floors": "Šildomos grindys",
        "fireplace": "Židinys",
    },
    "security": {
        "security_guard": "Budintis sargas",
        "coded_staircase_lock": "Kodinė laiptinės spyna",
        "alarm_system": "Signalizacija",
        "cctv": "Vaizdo kameros",
        "reinforced_door": "Šarvuotos durys",
    },
}